# Generated by Django 5.0.3 on 2024-08-15 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAuth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user'),
        ),
    ]
