# Generated by Django 5.0.3 on 2024-08-15 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAuth', '0002_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
