# Generated by Django 5.0.3 on 2024-08-20 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAuth', '0003_remove_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
