# Generated by Django 5.0.3 on 2024-07-10 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCategory', '0002_discountcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscountCategory',
        ),
    ]
