# Generated by Django 5.0.3 on 2024-08-15 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCategory', '0003_delete_discountcategory'),
        ('appStore', '0007_delete_brand_remove_review_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
