# Generated by Django 5.0.3 on 2024-08-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCategory', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoryName',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=13, unique=True),
        ),
    ]
