# Generated by Django 5.0.3 on 2024-08-18 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCategory', '0006_alter_category_categoryname_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='categoryDescription',
        ),
        migrations.RemoveField(
            model_name='category',
            name='categoryImage',
        ),
    ]
