# Generated by Django 5.0.3 on 2024-07-10 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appStore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandName', models.CharField(max_length=30, unique=True)),
                ('image', models.ImageField(upload_to='photos/brand')),
            ],
        ),
    ]
