# Generated by Django 5.0.3 on 2024-07-10 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCategory', '0001_initial'),
        ('appStore', '0002_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=40, unique=True)),
                ('slug', models.SlugField(max_length=45, unique=True)),
                ('productDescription', models.TextField(max_length=200)),
                ('price', models.IntegerField()),
                ('productImage', models.ImageField(upload_to='photos/product')),
                ('stock', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCategory.category')),
            ],
        ),
    ]
