# Generated by Django 5.0.3 on 2024-08-15 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCart', '0002_remove_cartitem_cart_remove_cartitem_product_and_more'),
        ('appOrder', '0002_remove_order_user_remove_orderproduct_order_and_more'),
        ('appStore', '0006_alter_product_discount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
