# Generated by Django 5.0.3 on 2024-08-15 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appStore', '0010_product_is_new'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeroArea',
        ),
    ]
