# Generated by Django 5.0.3 on 2024-08-15 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appStore', '0011_delete_heroarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/brand')),
            ],
        ),
    ]
