# Generated by Django 5.0.3 on 2024-07-10 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appOffer', '0002_discountproduct_discountprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountproduct',
            name='category',
        ),
        migrations.DeleteModel(
            name='DiscountCategory',
        ),
        migrations.DeleteModel(
            name='DiscountProduct',
        ),
    ]
